language: r
dist: xenial
cache: packages
branches:
    only:
        - master
r_packages:
    - rmarkdown

script:
    - Rscript -e 'rmarkdown::render("example.Rmd")'

before_deploy:
    - rm .gitignore

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAT
    on:
        branch: master
    target_branch: gh-pages
